(source gnu)
(source melpa)
(source org)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

;; Languages
(depends-on "org")
(depends-on "restclient")
(depends-on "ob-restclient")
(depends-on "company-restclient")
(depends-on "dockerfile-mode")
(depends-on "rjsx-mode")

(depends-on "evil")
(depends-on "sudo-edit")
(depends-on "projectile")
(depends-on "iflipb")
(depends-on "ace-jump-buffer")
(depends-on "avy")
(depends-on "ace-window")
(depends-on "magit")
(depends-on "evil-magit")
(depends-on "autopair")
(depends-on "company")
(depends-on "ensime")
(depends-on "flycheck")
(depends-on "ivy")
(depends-on "swiper")
(depends-on "counsel")
(depends-on "counsel-projectile")
(depends-on "spaceline")
(depends-on "winum")
(depends-on "neotree")
(depends-on "linum-relative")
(depends-on "which-key")
(depends-on "minimap")
(depends-on "general")

;; YAML
(depends-on "yaml-mode")

;; Rust lang
(depends-on "rust-mode")
(depends-on "flycheck-rust")
(depends-on "racer")
(depends-on "rust-snippets" :git "https://github.com/freebroccolo/rust-snippets.git")

;; clojure
(depends-on "cider")

;; Presentation
(depends-on "ox-reveal")

;; Themes
(depends-on "dracula-theme")
(depends-on "base16-theme")

(package "void config" "0.1.0" "void's config for emacs")
